### ISSUE TITLE
Genearates lines longer than the maximal line length

### ISSUE THREAD

**Issue by dathinab** [staktrace/quoted-printable#1]
Because you did not consider that adding `=\r\n` add additional
character, where the `=` count to the 76 chars line length limit
your code can generate lines with 79 characters (including `\r\n`
77 excluding) which is 1 characters longer than what the
maximal line length should be.

e.g. encoding:
`XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXY` 
(76 * `X`  + 1*`Y` )

will produce 
`XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=\r\nY`

so 76*`X` + 1*`=` and then the `\r\n`

but should produce:

`XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=\r\nXY`

**Comment by staktrace** [comment]
Fixed with 2d767f9. I published the build with the fix to crates.io as 0.3.2.
