### ISSUE TITLE
This crate does not seem to properly cope with newlines at the end of strings.

### ISSUE THREAD

**Issue by umanwizard** [staktrace/quoted-printable#13]

**Comment by umanwizard** [comment]
Sorry for the lack of description; I hit "enter" too fast.

This test fails, as it strips out the trailing `\r\n`:

```
#[test]
fn test_qp_rt() {
    let s = b"foo\r\n";
    let qp = quoted_printable::encode_to_str(s);
    let rt = quoted_printable::decode(&qp, quoted_printable::ParseMode::Strict).unwrap();
    assert_eq!(s.as_slice(), rt.as_slice());
}
```

**Comment by staktrace** [comment]
I believe this behaviour is expected per [the spec](https://www.rfc-editor.org/rfc/rfc2045#section-6.7). In particular, note this paragraph which indicates round-tripping text is not always guaranteed.

```
Because quoted-printable data is generally assumed to be line-
   oriented, it is to be expected that the representation of the breaks
   between the lines of quoted-printable data may be altered in
   transport, in the same manner that plain text mail has always been
   altered in Internet mail when passing between systems with differing
   newline conventions.  If such alterations are likely to constitute a
   corruption of the data, it is probably more sensible to use the
   base64 encoding rather than the quoted-printable encoding.
```

**Comment by umanwizard** [comment]
I think that comment merely points out that the breaks between lines of quoted-printable data might be modified in transit, not that the quoted-printable encoder is allowed to modify them itself. See for example this line from the spec:

> (4)   (Line Breaks) A line break in a text body, represented
          as a CRLF sequence in the text canonical form, must be
          represented by a ([RFC 822](https://www.rfc-editor.org/rfc/rfc822)) line break, which is also a
          CRLF sequence, in the Quoted-Printable encoding.
          

Anyway, even though the spec is a bit ambiguous about what is allowed, I think it's reasonable for this library to try to retain the property of round-tripping whenever possible (and indeed it is possible here)

**Comment by staktrace** [comment]
The encoder is keeping the CRLF. It's the decoder that's stripping it. If you print out the value of `qp` from your example it is the same as `s` because Rule 4 above is obeyed (it keeps the CRLF sequence). However on decoding the CRLF gets thrown away.

Can you provide more context on what you're trying to do that this issue is impacting?

**Comment by staktrace** [comment]
Ok, good to know, thanks. I'll take a closer look at this later in the week and see what other implementations do as well.

**Comment by staktrace** [comment]
After some consideration I think you're right. The decoder shouldn't have been stripping out the trailing newline so I'm fixing that in #16. Note however that round-tripping is still not guaranteed, e.g. if the input contains LF newlines, they will get converted to CRLF newlines. To handle that case I also added a binary mode encoding, which treats the input as binary and always encodes CRLF. That was in #14 .

**Comment by umanwizard** [comment]
Excellent, thanks for the fixes!
