### ISSUE TITLE
allow runtime specification of the LINE_LENGTH_LIMIT for rfc2047 header encoding purposes

### ISSUE THREAD

**Issue by wez** [staktrace/quoted-printable#18]
I realize that this isn't strictly necessary, but:

rfc2047 section 6.1.1:

> Beginning at the start of the field-body and immediately following each
       occurrence of 'linear-white-space', each sequence of up to 75
       printable characters (not containing any 'linear-white-space')
       should be examined to see if it is an 'encoded-word' according to
       the syntax rules in section 2

Section 2 describes the:

```
encoded-word = "=?" charset "?" encoding "?" encoded-text "?="
```

portion of the grammar.

My interpretation of this is that encoding such a header should allow for the closing `?=` to be within 75 chars of the opening `=?`.

Therefore it is desirable to be able to override the line length limit used by the internal `append` function so that the calling application can compute the length of the `=?charset?encoding??=` text and subtract that from 75 in order to set a "perfect" wrapping width.

What would be really nice would be to offer a rfc2047 header encoding function that will do that internally and generate wrapped and indented (with say a single `\t`) text with the `=?utf-8?q?<encoded-text>?=` already included!

Note that rfc2184 extends rfc2047 to define an optional language parameter: `=?charset*language?encoding?encoded-text?=`, so adding an optional `language` parameter would be desirable.

Would you be open to extending this crate with all or part of this functionality?

**Comment by staktrace** [comment]
Hm, interesting. I'm not keen on adding full rfc2047 header encoding functionality to this crate. However allowing a dynamic line length limit seems doable.

Question though, might it make more sense for this crate to expose a function like this?
```
encode_into<R: AsRef<[u8]>>(input: R, dest: &mut lib::String)
```

i.e. you would create a string, stick in your `=?charset?encoding?`, and pass that string in to `encode_into`. The lib would then encode the input directly onto the end of `dest` and ensure that the line being appended to doesn't exceed 75 characters.

Let me know if that makes sense and if that would solve your use case.

**Comment by wez** [comment]
I can understand not wanting to take on rfc2047.

The way I'm considering using this crate at the moment is:

* call `encode_to_str` on the text
* split it into lines
* For each line, strip the newlines, prepend `\t=?charset?encoding?` and append `?=\r\n`.  The rfc2047 decoration gets applied to each line of the qp encoded text.  The `\t` at the start is something that I may omit in some cases (eg: if the encoded word is going to be on the first line of a multi-line header), but otherwise include for subsequent lines produced by `encode_to_str`, or if we're calling this again for a different token that we're appending to a line.

I'd want each encoded line produced by `encode_to_str` (or whatever function gets added) to respect the limit I pass in, because I think trying to make that behavior implicit without making the implementation understand the rules around what is being bracketed around the lines is going to be mutually frustrating!  It feels simplest overall to expose a variant of the encoder with the limit parameter exposed.

**Comment by staktrace** [comment]
Sorry for the delay here. I think exposing the limit as an option makes sense. I put up a PR at https://github.com/staktrace/quoted-printable/pull/19, can you take a look and see if that would work for you? I need to add some docs but wanted to make sure it works for you before doing that. Thanks!

**Comment by wez** [comment]
I think that would work well, thanks!

**Comment by wez** [comment]
Thanks!
