### ISSUE TITLE
Do not trat `\r=` differently then `\r-` when encoding

### ISSUE THREAD

**Issue by dathinab** [staktrace/quoted-printable#3]
For some reason if there is a `\r` followed by an `=` the `\r` does not get encoded
(if fixed this in a branch from which I will make another pull request,
 which also includes some other improvements like using `AsRef`)

**Comment by staktrace** [comment]
Please keep improvements separate from correctness fixes. And feel free to submit PRs for improvements without filing issues beforehand.
